### ISSUE TITLE
Wrong error class for bootstrap component

### ISSUE THREAD

**Issue by PreVaDu** [chemix/try-flashmessage#1]
I found librette/flashMessages today and it is very useful. Thank you for that.

However I use Bootstrap3 and there is bug in Component/FlashMessages at line 19 - for error class should be alert-danger.

I would like to push edit, but I didn't find this in GitHub.

Thank you for any reply.

**Comment by chemix** [comment]
You mean this repository? https://github.com/librette/flash-messages

**Comment by chemix** [comment]
https://github.com/librette/flash-messages/blob/master/src/Component/FlashMessages.php#L19

**Comment by chemix** [comment]
but the question is if Bootstrap3 is primary supported. I think the class name danger is not good, and every time you can add your custom css class alert-error. But try it

**Comment by PreVaDu** [comment]
Thank you. Github search doesn't work well, I see...
Good question, you're right I could add it only in my project.
